title: TheTestMart Framework Documentation
description: A basic documentation website for TTM Framework
theme: just-the-docs

url: https://mycatt.github.io/miniature-umbrella/

aux_links:
  Template Repository: https://github.com/MyCatt/miniature-umbrella
